### ISSUE TITLE
Install fails on: "del ./build"

### ISSUE THREAD

**Issue by KerryRitter** [smartive/generator-giuseppe#7]
I tried to run the new version of the installer. The installer seems to work fine, but i can't run the project because "npm clean" is failing on "del ./build". the folder doesn't exist, but it still fails when i create.

i'm on Windows 10, running node 4.4.5. 

any suggestions would be helpful!

**Comment by buehler** [comment]
Oh my gosh.. windows 😄 
Let me / us have a look at it!

**Comment by Kaffiend** [comment]
an escaped `\\` should work fine.

**Comment by mfeltscher** [comment]
@KerryRitter This should be fixed with #11 - could you please test this and give us feedback? Thanks!
