### ISSUE TITLE
Feature request: DemoController with Passport authentication integration

### ISSUE THREAD

**Issue by KerryRitter** [smartive/generator-giuseppe#8]
It would be awesome if the generator could initialize the demo controller with passport integration set up on the demo controller when enabled. For somebody like me who is unfamiliar with Passport, this would be super helpful to get up and running.

**Comment by buehler** [comment]
Hey @KerryRitter 
It actually _should_™️  do that.

If you have a look @ the [AuthDemoController](https://github.com/smartive/generator-giuseppe/blob/master/app/templates/controllers/AuthDemoController.ts), there is a whole setup of passport authentication.

You'll need (example for bearer tokens):
Authentication setup [Authentication.ts](https://github.com/smartive/generator-giuseppe/blob/master/app/templates/Authentication.ts)

``` typescript
import passport = require('passport');
import {Strategy as BearerStrategy} from 'passport-http-bearer';
passport.use(new BearerStrategy((token, done) => {
    if (token === 'super-secret-bearer-token') {
        done(null, { user: 'bearer' });
        return;
    }
    done(null, false);
    // ! Do your authentication logic here! (i.e. database queries, whatever)
}));
export default passport;
```

The middleware registered into the controller or the route:
(AuthDemoController)

``` typescript
//Example if the whole controller should be secured
@Controller('secure/bearer/ctrl', passport.authenticate('bearer', { session: false }))
class BearerControllerAuth {
    @Get()
    public getSecure(): string {
        return 'Success.';
    }
}

//Example for a protected route
@Controller('secure/bearer/route')
class BearerRouteAuth {
    @Get('', passport.authenticate('bearer', { session: false }))
    public getSecure(): string {
        return 'Success.';
    }
}
```

Feel free to consult the documentation of giuseppe @ [giuseppe.smartive.ch](http://giuseppe.smartive.ch) and have a look at the examples @ [github](https://github.com/smartive/giuseppe/tree/master/examples)

Cheers
Chris

**Comment by buehler** [comment]
As an addition: of course the creation of the bearer tokens is on your behalf. You could use JWT for example.
Just make a login site, that is not secured (another controller maybe?), where the user can insert a username and a password. And with that information you can generate a JWT token, that the client on the web has to send over the wire to your application via the Authentication header.

`Authentication: Bearer <<token>>`

Cheers

**Comment by KerryRitter** [comment]
Ahhh. Tbh - i didn't know about those docs :D Feel free to close this!

**Comment by buehler** [comment]
Well if your question is answered ;-)
If not, reopen this ticket or open a ticket @ [giuseppe](https://github.com/smartive/giuseppe)
