### ISSUE TITLE
Use @Types

### ISSUE THREAD

**Issue by Kaffiend** [smartive/generator-giuseppe#9]
Should use @types declarations now. Need to add `typeRoots` to `tsconfig.json` and include `@types\mocha` and `@types\chai` as dev deps in `package.json`

**Comment by buehler** [comment]
@Kaffiend 
Hey there, thank you! Actually we are kind of making a version 2.x to support plugins as well. I don't know if `@types` is actually needed, when you deliver the `.d.ts` files with the package already.

**Comment by mfeltscher** [comment]
@buehler I don't think this is related to the new version we're working on. 
@Kaffiend Could you please create a pull request with the changes you mentioned?

**Comment by Kaffiend** [comment]
i noticed the 2.x branch, just a few moments, ago on the source, i really like the direction this project is headed. Sure ill take a look at it this evening.

**Comment by Kaffiend** [comment]
PR #10 submitted for review. I've never really worked with generators but this is what i had in mind, it removes the need for the typings directory and uses the newer @types delivery method.
